### ISSUE TITLE
Compile error in Rust 1.36.0

### ISSUE THREAD

**Issue by phiresky** [jgallagher/rusqlite#543]
rusqlite fails to compile on Rust 1.36.0:

```
   Compiling rusqlite v0.19.0
error[E0277]: `*const libsqlite3_sys::sqlite3_module` cannot be sent between threads safely
  --> /home/tehdog/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.19.0/src/vtab/series.rs:21:1
   |
21 | / lazy_static! {
22 | |     static ref SERIES_MODULE: Module<SeriesTab> = eponymous_only_module::<SeriesTab>(1);
23 | | }
   | |_^ `*const libsqlite3_sys::sqlite3_module` cannot be sent between threads safely
   |
   = help: within `vtab::Module<vtab::series::SeriesTab>`, the trait `std::marker::Send` is not implemented for `*const libsqlite3_sys::sqlite3_module`
   = note: required because it appears within the type `libsqlite3_sys::sqlite3_vtab`
   = note: required because it appears within the type `vtab::series::SeriesTab`
   = note: required because it appears within the type `std::marker::PhantomData<vtab::series::SeriesTab>`
   = note: required because it appears within the type `vtab::Module<vtab::series::SeriesTab>`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `spin::once::Once<vtab::Module<vtab::series::SeriesTab>>`
   = note: required because it appears within the type `lazy_static::lazy::Lazy<vtab::Module<vtab::series::SeriesTab>>`
   = note: shared static variables must have a type that implements `Sync`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0277]: `*mut i8` cannot be sent between threads safely
  --> /home/tehdog/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.19.0/src/vtab/series.rs:21:1
   |
21 | / lazy_static! {
22 | |     static ref SERIES_MODULE: Module<SeriesTab> = eponymous_only_module::<SeriesTab>(1);
23 | | }
   | |_^ `*mut i8` cannot be sent between threads safely
   |
   = help: within `vtab::Module<vtab::series::SeriesTab>`, the trait `std::marker::Send` is not implemented for `*mut i8`
   = note: required because it appears within the type `libsqlite3_sys::sqlite3_vtab`
   = note: required because it appears within the type `vtab::series::SeriesTab`
   = note: required because it appears within the type `std::marker::PhantomData<vtab::series::SeriesTab>`
   = note: required because it appears within the type `vtab::Module<vtab::series::SeriesTab>`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `spin::once::Once<vtab::Module<vtab::series::SeriesTab>>`
   = note: required because it appears within the type `lazy_static::lazy::Lazy<vtab::Module<vtab::series::SeriesTab>>`
   = note: shared static variables must have a type that implements `Sync`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `rusqlite`.

To learn more, run the command again with --verbose.
```

Seems to happen for both 0.19.0 and 0.18.0
Via this error report: https://github.com/phiresky/ripgrep-all/issues/22

**Comment by gwenn** [comment]
In the [original](https://www.sqlite.org/cgi/src/artifact/0c97f63378fddc9f) C version, `seriesModule` is static.
So I guess we can fix this by telling Rust that `sqlite3_module` is `Send` and `Sync`.
I will try to fix and add a test.
Thanks.

**Comment by gwenn** [comment]
I cannot reproduce the error...
But https://docs.rs/lazy_static/*/lazy_static/:
> Any type in them needs to fulfill the Sync trait.

```

**Comment by phiresky** [comment]
Uhh, could also be an interaction with some other library? Can you try and see if you get the error if you do `cargo install ripgrep_all`?

**Comment by gwenn** [comment]
I tried
```
$ git clone https://github.com/phiresky/ripgrep-all.git
$ cd ripgrep-all/
$ cargo +stable check 
```
And your Travis build seems ok.
And https://github.com/jgallagher/rusqlite/blob/master/src/vtab/mod.rs#L70:
```rust
unsafe impl<T: VTab> Sync for Module<T> {}
```
`Module` is `Sync` !

**Comment by phiresky** [comment]
to be honest, I don't know enough about rust to really understand what is happening.. 

`cargo +stable check` only started failing for me when I ran `cargo upgrade` and let it regenerate the lock file (try branch 1.36-weird)

**Comment by phiresky** [comment]
Oh yeah I should also mention I have vtab and bundled active

**Comment by Legogris** [comment]
Getting the same when running `cargo install riprep_all` with Cargo `1.35.0`

**Comment by thomcc** [comment]
Yeah, I can also repro, but building from the ripgrep-all repo works fine. Wonder if it's a rustc bug or something.

**Comment by gwenn** [comment]
When we say:
```
unsafe impl<T: VTab> Sync for Module<T> {}
```
Rust wants that `T` is `Send` ?

**Comment by gwenn** [comment]
Workaround:
It appears that you are only using the `vtab` feature for:
`rusqlite::vtab::escape_double_quote(&table)`
And you are not using it correctly:
`"select * from {}",`
should be:
`"select * from \"{}\"",`

Ideally, we would like to use [sqlite3_mprintf](http://sqlite.org/c3ref/mprintf.html) and "%w" but variadic args are not supported.

I am going to introduce a dedicated `series` feature.
So you should not have the compile error anymore.

**Comment by phiresky** [comment]
oh - guess that means an sqlite database do an sql injection on itself with my code :laughing: 

thanks for the effort!

**Comment by filalex77** [comment]
@gwenn  Can we get a release incorporating this fix? Thanks!

**Comment by gwenn** [comment]
@filalex77 I would like to merge #549 before.

**Comment by filalex77** [comment]
@gwenn Sure, thanks for the reply.

**Comment by gwenn** [comment]
Should be fixed by release 0.20.
